### ISSUE TITLE
Linux stop button fails.

### ISSUE THREAD

**Issue by MahdiRahbar** [mir-am/LIBTwinSVM#1] opened 2019-08-27 11:43 UTC

**Comment by mir-am** [comment] 2019-08-30 15:55
I could not reproduce this issue on my Linux system.
I think the issue can be solved by updating the dependencies of the library to the latest version (Especially the PyQT.).
I may close the issue.

**Closed as completed by mir-am** 2019-08-30 15:55 UTC

**Comment by mir-am** [comment] 2019-08-30 15:57
I could not reproduce this issue on my Linux system.
I think the issue can be solved by updating the dependencies of the library to the latest version (Especially the PyQT.).
I may close the issue.
